# ==============================
# Application
# ==============================
spring.application.name=log-layer

# ==============================
# Server
# ==============================
server.port=8082

# ==============================
# ML Service
# ==============================
#ml.service.base-url=http://localhost:8004
ml.service.base-url=http://localhost:8000
ml.service.predict-endpoint=/api/v1/predict
ml.service.health-endpoint=/api/v1/system/health
ml.service.train-endpoint=/api/v1/train
ml.service.timeout=5s
ml.service.retry-count=3

# ==============================
# PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/log_layer_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==============================
# Flyway
# ==============================
spring.flyway.enabled=false

# ==============================
# Jackson
# ==============================
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.serialization.write-dates-as-timestamps=false

# ==============================
# Logging
# ==============================
logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.web=INFO


# ==============================
# LLM Service
# ==============================
llm.service.base-url=http://localhost:8084
llm.service.analyze-endpoint=/api/v1/llm/analyze
llm.service.timeout=60s
