# ==============================
# Application
# ==============================
spring.application.name=demoUserService

# ==============================
# Server
# ==============================
server.port=8081

# ==============================
# PostgreSQL
# ==============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/devinsight
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# ==============================
# JPA
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
