package com.project.log_layer.repository;

import com.project.log_layer.entity.Log;
import com.project.log_layer.enums.Environment;
import com.project.log_layer.enums.LogLevel;
import com.project.log_layer.enums.LogStatus;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Repository for performing CRUD and search operations
 * on Log entities.
 */
public interface LogRepository extends JpaRepository<Log, Long>, JpaSpecificationExecutor<Log> {

    /**
     * Returns logs filtered by log level.
     */
    Page<Log> findByLevel(LogLevel level, Pageable pageable);

    /**
     * Returns logs generated by a specific service.
     */
    Page<Log> findByServiceName(String serviceName, Pageable pageable);

    /**
     * Returns all logs belonging to the same request.
     */
    Page<Log> findByCorrelationId(UUID correlationId, Pageable pageable);

    /**
     * Returns all anomalous logs.
     */
    Page<Log> findByAnomalyTrue(Pageable pageable);

    /**
     * Returns logs within the specified time range.
     */
    Page<Log> findByTimestampBetween(
            LocalDateTime start,
            LocalDateTime end,
            Pageable pageable
    );

    /**
     * Returns logs for a specific environment.
     */
    Page<Log> findByEnvironment(
            Environment environment,
            Pageable pageable
    );

    /**
     * Returns logs by processing status.
     */
    Page<Log> findByStatus(
            LogStatus status,
            Pageable pageable
    );

    /**
     * Searches log messages using a keyword.
     */
    @Query("""
            SELECT l
            FROM Log l
            WHERE LOWER(l.message)
            LIKE LOWER(CONCAT('%', :keyword, '%'))
            """)
    Page<Log> searchByMessage(
            String keyword,
            Pageable pageable
    );

}