package com.project.log_layer.dto.response.analysis;

import com.project.log_layer.dto.response.log.LogResponse;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

/**
 * Response DTO containing AI-generated analysis for a log.
 *
 * <p>This response combines the basic log information with
 * insights generated by the ML and LLM services.</p>
 *
 * <p>Composition is intentionally used instead of inheritance
 * to keep CRUD responses independent from AI-specific data.</p>
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LogAnalysisResponse {

    /**
     * Basic log information.
     */
    private LogResponse log;

    /**
     * AI-generated summary of the log.
     */
    private String summary;

    /**
     * AI-generated suggested resolution.
     */
    private String suggestedFix;

    /**
     * Most probable root cause identified by the AI.
     */
    private String probableRootCause;

    /**
     * Confidence score of the generated analysis.
     *
     * Range:
     * 0.0 - 1.0
     */
    private Double confidenceScore;

    /**
     * Ordered list of recommended actions.
     */
    private List<String> recommendedActions;

}