package com.project.log_layer.dto.response.log;

import com.project.log_layer.enums.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Response DTO returned to clients after processing a log.
 *
 * This DTO is consumed by:
 * - Dashboard
 * - REST APIs
 * - Future AI features
 */
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class LogResponse {

    /**
     * Unique database identifier.
     */
    private Long id;

    /**
     * Correlation identifier for distributed tracing.
     */
    private UUID correlationId;

    /**
     * Name of the application generating the log.
     */
    private String applicationName;

    /**
     * Timestamp of the log event.
     */
    private LocalDateTime timestamp;

    /**
     * Log severity.
     */
    private LogLevel level;

    /**
     * Service generating the log.
     */
    private String serviceName;

    /**
     * Fully qualified logger name.
     */
    private String loggerName;

    /**
     * Thread generating the log.
     */
    private String threadName;

    /**
     * Parsed log message.
     */
    private String message;

    /**
     * AI-generated short summary.
     *
     * Phase 1:
     * Equal to the message or a shortened version.
     *
     * Phase 3:
     * Generated by the LLM.
     */
    private String summary;

    /**
     * AI-generated suggested resolution.
     *
     * Phase 1:
     * Null.
     *
     * Phase 3:
     * Generated by the LLM.
     */
    private String suggestedFix;

    /**
     * Source of the log.
     */
    private LogSource source;

    /**
     * Host, VM, Pod or Container name.
     */
    private String hostName;

    /**
     * Deployment environment.
     */
    private Environment environment;

    /**
     * Processing status.
     */
    private LogStatus status;

    /**
     * Whether ML detected an anomaly.
     */
    private Boolean anomaly;

    /**
     * ML confidence score.
     */
    private Double anomalyScore;

    /**
     * Time the log was persisted.
     */
    private LocalDateTime createdAt;

    private Integer prediction;

    private String predictionLabel;

    private Double decisionScore;

    private String modelVersion;

    private AnalysisStatus analysisStatus;

    private LocalDateTime analyzedAt;
}