"""
===============================================================================
DevInsight AI - Feature Type Definitions
===============================================================================

Defines the datatype of every feature generated by the Feature Engineering
pipeline.

This module acts as the single source of truth for feature datatypes.

Author : DevInsight AI
Version: 1.0.0
===============================================================================
"""

from enum import Enum
from typing import Final

from app.features.feature_names import FEATURE_NAMES


# =============================================================================
# Feature Types
# =============================================================================


class FeatureType(str, Enum):
    """
    Supported feature datatypes.
    """

    NUMERIC = "numeric"
    BOOLEAN = "boolean"
    CATEGORICAL = "categorical"


# =============================================================================
# Metadata Features
# =============================================================================

METADATA_FEATURE_TYPES: Final[dict[str, FeatureType]] = {
    "log_level": FeatureType.CATEGORICAL,
    "service_hash": FeatureType.CATEGORICAL,
    "hour_of_day": FeatureType.CATEGORICAL,
    "day_of_week": FeatureType.CATEGORICAL,
}

# =============================================================================
# Text Features
# =============================================================================

TEXT_FEATURE_TYPES: Final[dict[str, FeatureType]] = {
    "message_length": FeatureType.NUMERIC,
    "token_count": FeatureType.NUMERIC,
    "average_word_length": FeatureType.NUMERIC,
    "uppercase_ratio": FeatureType.NUMERIC,
    "lowercase_ratio": FeatureType.NUMERIC,
    "digit_ratio": FeatureType.NUMERIC,
    "alphabetic_ratio": FeatureType.NUMERIC,
    "special_character_ratio": FeatureType.NUMERIC,
    "longest_token_length": FeatureType.NUMERIC,
    "shortest_token_length": FeatureType.NUMERIC,
    "average_token_length_variance": FeatureType.NUMERIC,
    "whitespace_ratio": FeatureType.NUMERIC,
    "contains_mixed_case": FeatureType.BOOLEAN,
    "starts_with_timestamp": FeatureType.BOOLEAN,
    "empty_message": FeatureType.BOOLEAN,
}

# =============================================================================
# Statistical Features
# =============================================================================

STATISTICAL_FEATURE_TYPES: Final[dict[str, FeatureType]] = {

    "entropy": FeatureType.NUMERIC,

    "unique_token_ratio": FeatureType.NUMERIC,

    "character_diversity": FeatureType.NUMERIC,

    "punctuation_ratio": FeatureType.NUMERIC,

    "numeric_density": FeatureType.NUMERIC,

    "average_line_length": FeatureType.NUMERIC,

    "line_count": FeatureType.NUMERIC,

}

# =============================================================================
# Regex Features
# =============================================================================

REGEX_FEATURE_TYPES: Final[dict[str, FeatureType]] = {
    "contains_exception": FeatureType.BOOLEAN,
    "contains_stacktrace": FeatureType.BOOLEAN,
    "contains_timeout": FeatureType.BOOLEAN,
    "contains_database_error": FeatureType.BOOLEAN,
    "contains_network_error": FeatureType.BOOLEAN,
    "contains_memory_error": FeatureType.BOOLEAN,
    "contains_http_status": FeatureType.BOOLEAN,
    "contains_ip_address": FeatureType.BOOLEAN,
    "contains_uuid": FeatureType.BOOLEAN,
    "contains_port_number": FeatureType.BOOLEAN,
    "contains_kubernetes_keyword": FeatureType.BOOLEAN,
    "contains_docker_keyword": FeatureType.BOOLEAN,
    "contains_spring_keyword": FeatureType.BOOLEAN,
    "contains_jvm_keyword": FeatureType.BOOLEAN,
    "contains_authentication_keyword": FeatureType.BOOLEAN,
}

# =============================================================================
# Combined Registry
# =============================================================================

FEATURE_TYPES: Final[dict[str, FeatureType]] = {
    **METADATA_FEATURE_TYPES,
    **TEXT_FEATURE_TYPES,
    **STATISTICAL_FEATURE_TYPES,
    **REGEX_FEATURE_TYPES,
}

# =============================================================================
# Validation
# =============================================================================

_missing = set(FEATURE_NAMES) - set(FEATURE_TYPES.keys())
_extra = set(FEATURE_TYPES.keys()) - set(FEATURE_NAMES)

if _missing:
    raise RuntimeError(
        f"Missing feature type definitions: {sorted(_missing)}"
    )

if _extra:
    raise RuntimeError(
        f"Unknown feature type definitions: {sorted(_extra)}"
    )